### ISSUE TITLE
Statement "resume" really should be restrict to "effect" block?

### ISSUE THREAD

**Issue by macabeus** [macabeus/js-proposal-algebraic-effects#9]
This code works fine:
```
const foo = () => 1

try {
  ...
} effect {
  resume foo()
}
```

But this not:

```
const foo = () => { resume 1 }

try {
  ...
} effect {
  foo()
}
```

It happens because, at this moment, `resume` only work inside of `effect` block. But is it really good? Should we keep this behaviour or change it?

**Comment by luizperes** [comment]
Wait, what happens if you never call `resume` in a `handle effect` block?

**Comment by macabeus** [comment]
@luizperes there is an issue to discuss about that: https://github.com/macabeus/js-proposal-algebraic-effects/issues/8

**Comment by macabeus** [comment]
I'm closing this issue because we decides [here](https://github.com/macabeus/js-proposal-algebraic-effects/issues/8) to not allow it.
